### ISSUE TITLE
where is the processed data

### ISSUE THREAD

**Issue by marramWang** [bioliyezhang/HCC_Metastasis#1]
hi, where is the processed data you mentioned in README.md

**Comment by bioliyezhang** [comment]
Hi, Marram

    Majority of the processed data is included in the Supplementary Material and some others are deposited into the public data archive website. The raw sequence data reported in this paper have been deposited in the Genome Sequence Archive121 in National Genomics Data Center,122 Beijing Institute of Genomics (BIG), Chinese Academy of Sciences, under accession number GSA-Human: HRA001272 and GSA-Human: HRA005479 that are publicly accessible at https://ngdc.cncb.ac.cn/gsa. 
     If this does not answer your question, please be more specific on which processed data you are looking for.

Best,
